"""empty message

Revision ID: 070195b3b452
Revises: 3b972ef6198c
Create Date: 2026-04-24 21:03:32.758063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070195b3b452'
down_revision = '3b972ef6198c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('detalles', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=250), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividad')
    op.drop_table('rutina')
    # ### end Alembic commands ###
