"""empty message

Revision ID: 1d3b2e5ca6a5
Revises: 070195b3b452
Create Date: 2026-04-25 17:47:56.374857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3b2e5ca6a5'
down_revision = '070195b3b452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignacion_rutina',
    sa.Column('hijo_id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hijo_id'], ['hijo.id'], ),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutina.id'], ),
    sa.PrimaryKeyConstraint('hijo_id', 'rutina_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asignacion_rutina')
    # ### end Alembic commands ###
