"""empty message

Revision ID: 3b972ef6198c
Revises: bdc8d44ab3ac
Create Date: 2026-04-23 09:55:28.882333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b972ef6198c'
down_revision = 'bdc8d44ab3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hijo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('info_adicional', sa.Text(), nullable=True),
    sa.Column('intolerancia', sa.String(length=100), nullable=True),
    sa.Column('alergia', sa.String(length=100), nullable=True),
    sa.Column('asma', sa.String(length=50), nullable=True),
    sa.Column('tipo_sangre', sa.String(length=10), nullable=False),
    sa.Column('gatea', sa.String(length=10), nullable=True),
    sa.Column('autonomia_bano', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autorizado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=80), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('parentesco', sa.String(length=50), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('es_permanente', sa.Boolean(), nullable=True),
    sa.Column('valido_desde', sa.String(length=20), nullable=True),
    sa.Column('valido_hasta', sa.String(length=20), nullable=True),
    sa.Column('hijo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hijo_id'], ['hijo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autorizado')
    op.drop_table('hijo')
    # ### end Alembic commands ###
