"""empty message

Revision ID: ba08d68592c6
Revises: 1d3b2e5ca6a5
Create Date: 2026-04-27 07:06:31.747029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba08d68592c6'
down_revision = '1d3b2e5ca6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutina_compartida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuidador_id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.Column('hijo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuidador_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['hijo_id'], ['hijo.id'], ),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rutina_compartida')
    # ### end Alembic commands ###
