"""empty message

Revision ID: bdc8d44ab3ac
Revises: 0763d677d453
Create Date: 2026-04-14 21:18:15.093608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc8d44ab3ac'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('edad', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('direccion_hogar', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('direccion_trabajo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion_trabajo')
        batch_op.drop_column('direccion_hogar')
        batch_op.drop_column('edad')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
